services:
  db:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: chatapp
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build: ./chat-be
    container_name: fastapi
    env_file:
      - ./chat-be/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: >
      sh -c "
        alembic upgrade head &&
        uvicorn main:app --host 0.0.0.0 --port 8000
      "

volumes:
  db_data: